/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  rapidoSidebar: [
    'intro',
    'booking-ride',
    'common-issues',
    {
      type: 'category',
      label: 'Order Booking Issues',
      items: [
        {
          type: 'autogenerated',
          dirName: 'order-booking',
        },
      ],
    },
  ],
};
